---
- name: Install IBM watsonx.ai
  hosts: localhost

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    log_level: "info"
    cloud_pak:
      version: "5.1"
      license_accepted: false
      branch: "main"
    operator:
      scope: "namespace"
      namespace: "ibmint"
    instance:
      name: "integration-quickstart"
      namespace: "ibmint"
    instance_default:
      retries: 90
      retry_delay: 60
    directories:
      bin_dir: "/usr/local/bin"
      tmp_dir: "/tmp"
    default:
      retries: 60
      retry_delay: 15

  tasks:

    - name: Install podman and jq
      ansible.builtin.package:
        name: 
          - podman
          - jq
        state: latest

    - name: Check if oc client is already installed
      ansible.builtin.stat:
        path: "{{ directories.bin_dir }}/oc"
      register: oc_file

    - name: Install oc client if not already installed
      ansible.builtin.include_tasks:
        file: install-oc.yaml
      when: not oc_file.stat.exists

    - name: Check if already logged into cluster
      ansible.builtin.shell: |
        set timeout 30
        {{ directories.bin_dir }}/oc status 2> /dev/null
        exit 0
      args:
        executable: /bin/bash
      register: response

    - name: Login to OpenShift cluster if not already logged in
      ansible.builtin.include_tasks:
        file: ./oc-login.yaml
      when: response.stdout == ""

    - name: Create template directory if not already in place
      ansible.builtin.file:
        path: ./templates
        state: directory
      
    # Following is required as some implementations download templates and playbooks to a single directory
    - name: Copy templates to template directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: ./templates/
      with_fileglob:
        - ./*.j2

    # - name: Create the ODF machinesets and storage cluster

    # - name: Create the GPU machineset

    # - name: Install and configure Red Hat Node Feature Discovery Tool

    # - name: Install and configure the Nvidia Driver

    # - name: Install and configure Red Hat OpenShift AI

    # - name: Install the base Cloud Pak components

    # - name: Install watsonx.ai

    # - name: Add the foundation models