---
- name: Install Instana standard on a RHEL virtual machine
  hosts: localhost

  vars:
    instana:
      download_key: ""
      sales_key: ""
      tenant_name: ""
      unit_name: ""
      accept_license: false
      admin_password: ""
    tls:
      cert: ""
      key: ""
    vm:
    dir:
      tmp_dir: "/tmp"
      bin_dir: "/usr/local/bin"


  tasks: 
  
  # - name: Prepare additional disks

  # - name: Configure kernel parameters

  # - name: Add bin directory (for RHEL)

  # - name: Add Instana repository

  # - name: Install stanctl command-line tool

  # - name: Install Instana

