---
- name: Install Instana standard on a RHEL virtual machine
  hosts: localhost
  gather_facts: yes

  vars:
    instana:
      download_key: ""
      sales_key: ""
      tenant_name: ""
      unit_name: ""
      accept_license: false
      admin_password: ""
    tls:
      cert: ""
      key: ""
    vm:
    disks:
      - name: data
        size: "150.00 GB"
        mount_point: "/mnt/instana/stanctl/data"
      - name: metrics
        size: "300.00 GB"
        mount_point: "/mnt/instana/stanctl/metrics"
      - name: analytics
        size: "500.00 GB"
        mount_point: "/mnt/instana/stanctl/analytics"  
      - name: objects
        size: "500.00 GB"
        mount_point: "/mnt/instana/stanctl/objects"           
    dir:
      tmp_dir: "/tmp"
      bin_dir: "/usr/local/bin"


  tasks: 

  - name: Prepare additional disks
    ansible.builtin.include_tasks:
      file: ./prepare-disks.yaml
    loop: "{{ disks }}"
    loop_control:
      loop_var: disk_item

  # - name: Configure kernel parameters

  # - name: Add bin directory (for RHEL)

  # - name: Add Instana repository

  # - name: Install stanctl command-line tool

  # - name: Install Instana

