---

- name: Check if az cli exists
  ansible.builtin.shell: |
    set timeout 5
    which az 2> /dev/null
    exit 0
  register: response

- name: Set fact based on response (az exists)
  ansible.builtin.set_fact:
    az_exists: "{{ True if( response.stdout != '' ) else False }}"

- name: Install Azure CLI
  when: not az_exists
  block:
    
    - name: Import the Microsoft repository key
      ansible.builtin.shell:
        cmd: "rpm --import https://packages.microsoft.com/keys/microsoft.asc"

    - name: Add the packages-microsoft-com-prod repository
      ansible.builtin.shell:
        cmd: "dnf install -y https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm"

    - name: Install the Azure CLI package
      ansible.builtin.shell:
        cmd: "dnf install -y azure-cli"

- name: Check if already logged into Azure CLI
  ansible.builtin.shell: |
    set timeout 5
    az account show 2> /dev/null
    exit 0
  register: response

- name: Set fact based on response (az cli logged in)
  ansible.builtin.set_fact:
    az_logged_in: "{{ True if( response.stdout != '') else False }}"

- name: Log into the Azure CLI
  when: not az_logged_in
  block:
  - name: Login into Azure CLI
    ansible.builtin.shell:
      cmd: "az login --identity"
    register: result

  - name: Output login result
    ansible.builtin.debug:
      var: result
    when: log_level == "debug"