---

- name: Get existing labelled nodes in zone {{ zone }}
  set_fact:
    labelled_nodes: "{{ node_details | selectattr('zone', 'equalto', zone) | selectattr('labelled', 'equalto', true) | map(attribute='name') | list }}"

- name: Output already labelled label found
  ansible.builtin.debug:
    msg: "INFO: Found {{ labelled_nodes }} in zone {{ zone }} already labelled for OCS"
  when: labelled_nodes | length > 0

- name: Get unlabelled nodes from zone {{ zone }}
  ansible.builtin.set_fact:
    odf_nodes: "{{ node_details | selectattr('zone', 'equalto', zone) | selectattr('labelled', 'equalto', false) | selectattr('cpu', '>=', '16') | map(attribute='name') | list }}"
  when: labelled_nodes | length == 0

- name: Fail if no nodes available or already labelled in zone {{ zone }}
  ansible.builtin.fail:
    msg: "No compatible nodes found in zone {{ zone }}"
  when: 
    - labelled_nodes | length == 0
    - odf_nodes | length == 0

- name: Label a new node for ODF in zone {{ zone }}
  ansible.builtin.command: "{{ directories.bin_dir }}/oc label node {{ odf_nodes[0] }} cluster.ocs.openshift.io/openshift-storage=''"
  when: odf_nodes | length > 0

- name: Log the action of labelling node
  ansible.builtin.debug:
    msg: "INFO: Labelling {{ odf_nodes[0] }} as ODF node for availability zone {{ zone }}"
  when: odf_nodes | length > 0